# Generated by Django 2.2.7 on 2019-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_service', '0004_accounts_exdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='number_of_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='seller_rating',
            field=models.FloatField(null=True),
        ),
    ]
