# Generated by Django 2.0.13 on 2019-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_service', '0006_auto_20191117_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='address_zip',
            field=models.CharField(max_length=5),
        ),
    ]
