# Generated by Django 2.0.13 on 2019-11-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_service', '0007_auto_20191118_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='account_id',
        ),
        migrations.DeleteModel(
            name='Watchlists',
        ),
    ]
