# Generated by Django 2.2.6 on 2019-11-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='buy_now',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='items',
            name='shipping_costs',
        ),
        migrations.RemoveField(
            model_name='items',
            name='start_price',
        ),
        migrations.AddField(
            model_name='items',
            name='account_id',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='in_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
