# Generated by Django 2.2.6 on 2019-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0003_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auction_id',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
