# Generated by Django 2.2.6 on 2019-11-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0005_auto_20191105_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='auction_id',
        ),
    ]
