# Generated by Django 2.2.6 on 2019-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0006_remove_items_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auction_id',
            field=models.IntegerField(null=True),
        ),
    ]
