# Generated by Django 2.2.6 on 2019-11-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0007_items_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cart_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='sold_to',
            field=models.IntegerField(null=True),
        ),
    ]
