# Generated by Django 2.2.6 on 2019-11-09 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0009_auto_20191109_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auction_end_notif_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='auction_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='auction_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
