# Generated by Django 2.2.6 on 2019-11-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0010_auto_20191109_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='auction_exists',
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AlterField(
            model_name='items',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='items_service.Categories'),
        ),
    ]
