# Generated by Django 2.2.6 on 2019-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0013_remove_items_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
