# Generated by Django 2.2.6 on 2019-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0015_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='items_service.Categories'),
        ),
    ]
