# Generated by Django 2.2.7 on 2019-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0019_items_admin_stopped_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='cart_id',
            new_name='cart_account_id',
        ),
    ]
