# Generated by Django 2.2.7 on 2019-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0020_auto_20191115_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='buy_now_price',
            field=models.FloatField(default=True),
        ),
    ]
