# Generated by Django 2.0.13 on 2019-11-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0021_items_buy_now_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='buy_now_price',
            field=models.FloatField(null=True),
        ),
    ]
