# Generated by Django 2.0.13 on 2019-11-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0022_auto_20191125_2251'),
        ('items_service', '0022_auto_20191125_2052'),
    ]

    operations = [
    ]
