# Generated by Django 2.0.13 on 2019-11-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_service', '0023_merge_20191126_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='start_price',
            field=models.FloatField(null=True),
        ),
    ]
