# Generated by Django 2.2.7 on 2019-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.IntegerField(default=0)),
                ('seller_account_id', models.IntegerField(default=0)),
                ('seller_email', models.CharField(max_length=150)),
                ('buyer_account_id', models.IntegerField(default=0)),
                ('buyer_email', models.CharField(max_length=150)),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(max_length=200)),
                ('highest_bid', models.BooleanField(default=False)),
            ],
        ),
    ]
