# Generated by Django 2.2.7 on 2019-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='most_current_bid',
            field=models.BooleanField(default=False),
        ),
    ]
