# Generated by Django 2.2.7 on 2019-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_service', '0002_bids_most_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.FloatField(default=0),
        ),
    ]
