# Generated by Django 2.2.7 on 2019-11-26 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_service', '0003_auto_20191124_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
