# Generated by Django 2.2.7 on 2019-11-15 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='in_cart_from',
            field=models.CharField(default='Not important', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('cardno', models.CharField(max_length=16)),
                ('scode', models.CharField(max_length=4)),
                ('exdate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('bzc', models.CharField(max_length=5)),
                ('adr', models.CharField(max_length=100)),
                ('adr2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('cart_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_service.Carts')),
            ],
        ),
    ]
