# Generated by Django 2.2.7 on 2019-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_service', '0002_auto_20191115_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='in_cart_from',
        ),
        migrations.AddField(
            model_name='carts',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
