# Generated by Django 2.2.7 on 2019-11-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_service', '0003_auto_20191115_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='adr2',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exdate',
            field=models.CharField(default='01/2020', max_length=7),
            preserve_default=False,
        ),
    ]
