# Generated by Django 2.0.13 on 2019-11-20 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts_service', '0005_remove_transactions_bzc'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='in_cart_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
